website/events/urls.py
"""Routes defined by the events package"""
from django.urls import path, include

from events.feeds import EventFeed
from events.views import (
    EventIndex,
    EventDetail,
    EventRegisterView,
    RegistrationView,
    EventCancelView,
    AlumniEventsView,
    EventPayView,
)

app_name = "events"

urlpatterns = [
    path(
        "events/",
        include(
            [
                path("<int:pk>/", EventDetail.as_view(), name="event"),
                path(
                    "<int:pk>/registration/register/",
                    EventRegisterView.as_view(),
                    name="register",
                ),
                path(
                    "<int:pk>/registration/cancel/",
                    EventCancelView.as_view(),
                    name="cancel",
                ),
                path("<int:pk>/registration/pay/", EventPayView.as_view(), name="pay"),
                path(
                    "<int:pk>/registration/",
                    RegistrationView.as_view(),
                    name="registration",
                ),
                path("", EventIndex.as_view(), name="index"),
                path("ical/nl.ics", EventFeed(lang="nl"), name="ical-nl"),
                path("ical/en.ics", EventFeed(), name="ical-en"),
            ]
        ),
    ),
    path("association/alumni/", AlumniEventsView.as_view(), name="alumni"),
]

website/members/api/urls.py
"""DRF routes defined by the members package"""
from rest_framework import routers

from members.api import viewsets

router = routers.SimpleRouter()
router.register(r"members", viewsets.MemberViewset)
urlpatterns = router.urls

website/members/urls.py
"""The routes defined by the members package"""
from django.urls import path, include

from members.views import (
    MembersIndex,
    StatisticsView,
    ProfileDetailView,
    UserAccountView,
    UserProfileUpdateView,
    EmailChangeFormView,
    EmailChangeVerifyView,
    EmailChangeConfirmView,
)

app_name = "members"

urlpatterns = [
    path(
        "members/",
        include(
            [
                path("statistics/", StatisticsView.as_view(), name="statistics"),
                path("profile/<int:pk>", ProfileDetailView.as_view(), name="profile"),
                path("directory/<slug:filter>/", MembersIndex.as_view(), name="index"),
                path("directory/", MembersIndex.as_view(), name="index"),
            ]
        ),
    ),
    path(
        "user/",
        include(
            [
                path(
                    "edit-profile/",
                    UserProfileUpdateView.as_view(),
                    name="edit-profile",
                ),
                path(
                    "change-email/verify/<uuid:key>/",
                    EmailChangeVerifyView.as_view(),
                    name="email-change-verify",
                ),
                path(
                    "change-email/confirm/<uuid:key>/",
                    EmailChangeConfirmView.as_view(),
                    name="email-change-confirm",
                ),
                path(
                    "change-email/", EmailChangeFormView.as_view(), name="email-change"
                ),
                path("", UserAccountView.as_view(), name="user"),
            ]
        ),
    ),
]

website/payments/urls.py
from django.urls import path, include

from .views import (
    BankAccountCreateView,
    BankAccountListView,
    BankAccountRevokeView,
    PaymentListView,
)

app_name = "payments"

urlpatterns = [
    path(
        "user/finance/",
        include(
            [
                path(
                    "accounts/",
                    include(
                        [
                            path(
                                "",
                                BankAccountListView.as_view(),
                                name="bankaccount-list",
                            ),
                            path(
                                "add/",
                                BankAccountCreateView.as_view(),
                                name="bankaccount-add",
                            ),
                            path(
                                "<uuid:pk>/revoke/",
                                BankAccountRevokeView.as_view(),
                                name="bankaccount-revoke",
                            ),
                        ]
                    ),
                ),
                path(
                    "payments/",
                    include(
                        [
                            path("", PaymentListView.as_view(), name="payment-list"),
                            path(
                                "<int:year>-<int:month>/",
                                PaymentListView.as_view(),
                                name="payment-list",
                            ),
                        ]
                    ),
                ),
            ]
        ),
    )
]

website/registrations/urls.py
"""The routes defined by the registrations package"""
from django.urls import path, include
from django.views.generic import TemplateView

from .views import (
    BecomeAMemberView,
    ConfirmEmailView,
    EntryAdminView,
    MemberRegistrationFormView,
    RenewalFormView,
    BenefactorRegistrationFormView,
    ReferenceCreateView,
)

app_name = "registrations"

urlpatterns = [
    path(
        "registration/",
        include(
            [
                path(
                    "admin/process/<uuid:pk>/",
                    EntryAdminView.as_view(),
                    name="admin-process",
                ),
                path(
                    "confirm-email/<uuid:pk>/",
                    ConfirmEmailView.as_view(),
                    name="confirm-email",
                ),
                path(
                    "reference/<uuid:pk>/",
                    ReferenceCreateView.as_view(),
                    name="reference",
                ),
                path(
                    "reference/<uuid:pk>/success",
                    ReferenceCreateView.as_view(success=True),
                    name="reference-success",
                ),
            ]
        ),
    ),
    path(
        "user/membership/",
        include(
            [
                path("", RenewalFormView.as_view(), name="renew"),
                path(
                    "renew/success/",
                    TemplateView.as_view(
                        template_name="registrations/renewal_success.html"
                    ),
                    name="renew-success",
                ),
            ]
        ),
    ),
    path(
        "association/",
        include(
            [
                path("register/", BecomeAMemberView.as_view(), name="index"),
                path(
                    "register/member/",
                    MemberRegistrationFormView.as_view(),
                    name="register-member",
                ),
                path(
                    "register/benefactor/",
                    BenefactorRegistrationFormView.as_view(),
                    name="register-benefactor",
                ),
                path(
                    "register/success/",
                    TemplateView.as_view(
                        template_name="registrations/register_success.html"
                    ),
                    name="register-success",
                ),
            ]
        ),
    ),
]

website/members/models.py
"""Models defined in the members package"""
import logging
import operator
import os
import uuid
from datetime import timedelta
from functools import reduce

from PIL import Image
from django.conf import settings
from django.contrib.auth.models import User, UserManager
from django.core import validators
from django.core.exceptions import ValidationError
from django.core.files.storage import DefaultStorage
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.translation import pgettext_lazy, gettext_lazy as _

from payments.models import BankAccount
from activemembers.models import MemberGroup, MemberGroupMembership
from utils import countries

logger = logging.getLogger(__name__)


class MemberManager(UserManager):
    """Get all members, i.e. all users with a profile."""

    def get_queryset(self):
        return super().get_queryset().exclude(profile=None)


class ActiveMemberManager(MemberManager):
    """Get all active members, i.e. who have a committee membership"""

    def get_queryset(self):
        """Select all committee members"""
        active_memberships = MemberGroupMembership.active_objects.filter(
            group__board=None
        ).filter(group__society=None)

        return (
            super()
            .get_queryset()
            .filter(membergroupmembership__in=active_memberships)
            .distinct()
        )


class CurrentMemberManager(MemberManager):
    """Get all members with an active membership"""

    def get_queryset(self):
        """
        Select all members who have a current membership
        """
        return (
            super()
            .get_queryset()
            .exclude(membership=None)
            .filter(
                Q(membership__until__isnull=True)
                | Q(membership__until__gt=timezone.now().date())
            )
            .distinct()
        )

    def with_birthdays_in_range(self, from_date, to_date):
        """
        Select all who are currently a Thalia member and have a
        birthday within the specified range

        :param from_date: the start of the range (inclusive)
        :param to_date: the end of the range (inclusive)
        :paramtype from_date: datetime
        :paramtype to_date: datetime

        :return: the filtered queryset
        :rtype: Queryset
        """
        queryset = self.get_queryset().filter(profile__birthday__lte=to_date)

        if (to_date - from_date).days >= 366:
            # 366 is important to also account for leap years
            # Everyone that's born before to_date has a birthday
            return queryset

        delta = to_date - from_date
        dates = [from_date + timedelta(days=i) for i in range(delta.days + 1)]
        monthdays = [
            {"profile__birthday__month": d.month, "profile__birthday__day": d.day}
            for d in dates
        ]
        # Don't get me started (basically, we are making a giant OR query with
        # all days and months that are in the range)
        query = reduce(operator.or_, [Q(**d) for d in monthdays])
        return queryset.filter(query)


class Member(User):
    class Meta:
        proxy = True
        ordering = ("first_name", "last_name")
        permissions = (("nextcloud_admin", _("Access NextCloud as admin")),)

    objects = MemberManager()
    current_members = CurrentMemberManager()
    active_members = ActiveMemberManager()

    def __str__(self):
        return "{} ({})".format(self.get_full_name(), self.username)

    @property
    def current_membership(self):
        """
        The currently active membership of the user. None if not active.

        :return: the currently active membership or None
        :rtype: Membership or None
        """
        membership = self.latest_membership
        if membership and not membership.is_active():
            return None
        return membership

    @property
    def latest_membership(self):
        """Get the most recent membership of this user"""
        if not self.membership_set.exists():
            return None
        return self.membership_set.latest("since")

    @property
    def earliest_membership(self):
        """Get the earliest membership of this user"""
        if not self.membership_set.exists():
            return None
        return self.membership_set.earliest("since")

    def has_been_member(self):
        """Has this user ever been a member?"""
        return self.membership_set.filter(type="member").count() > 0

    def has_been_honorary_member(self):
        """Has this user ever been an honorary member?"""
        return self.membership_set.filter(type="honorary").count() > 0

    def has_active_membership(self):
        """Is this member currently active

        Tested by checking if the expiration date has passed.
        """
        return self.current_membership is not None

    # Special properties for admin site
    has_active_membership.boolean = True
    has_active_membership.short_description = _("Is this user currently active")

    @classmethod
    def all_with_membership(cls, membership_type):
        """
        Get all users who have a specific membership.

        :param membership_type: The membership to select by
        :return: List of users
        :rtype: [Member]
        """
        return [
            x
            for x in cls.objects.all()
            if x.current_membership and x.current_membership.type == membership_type
        ]

    @property
    def can_attend_events(self):
        """May this user attend events"""
        if not self.profile:
            return False

        return (
            self.profile.event_permissions == "all"
            or self.profile.event_permissions == "no_drinks"
        ) and self.current_membership is not None

    def get_member_groups(self):
        """Get the groups this user is a member of"""
        return MemberGroup.objects.filter(
            Q(membergroupmembership__member=self)
            & (
                Q(membergroupmembership__until=None)
                | Q(membergroupmembership__until__gt=timezone.now())
            )
        ).exclude(active=False)

    def get_absolute_url(self):
        return reverse("members:profile", args=[str(self.pk)])

    @property
    def tpay_enabled(self):
        """Does this user have a bank account with Direct Debit enabled"""
        bank_accounts = BankAccount.objects.filter(owner=self)
        return (
            settings.THALIA_PAY_ENABLED_PAYMENT_METHOD
            and bank_accounts.exists()
            and bank_accounts.last().valid
        )


def _profile_image_path(_instance, _filename):
    """
    Sets the upload path for profile images.

    Makes sure that it's hard to enumerate profile images.

    Also makes sure any user-picked filenames don't survive

    >>> _profile_image_path(None, "bla.jpg")
    public/avatars/...
    >>> "swearword" in _profile_image_path(None, "swearword.jpg")
    False
    """
    return f"public/avatars/{get_random_string(length=16)}"


class Profile(models.Model):
    """This class holds extra information about a member"""

    # No longer yearly membership as a type, use expiration date instead.
    PROGRAMME_CHOICES = (
        ("computingscience", _("Computing Science")),
        ("informationscience", _("Information Sciences")),
    )

    # Preferably this would have been a foreign key to Member instead,
    # but the UserAdmin requires that this is a foreign key to User.
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)

    # ----- Registration information -----

    programme = models.CharField(
        max_length=20,
        choices=PROGRAMME_CHOICES,
        verbose_name=_("Study programme"),
        blank=True,
        null=True,
    )

    student_number = models.CharField(
        verbose_name=_("Student number"),
        max_length=8,
        validators=[
            validators.RegexValidator(
                regex=r"(s\d{7}|[ezu]\d{6,7})",
                message=_("Enter a valid student- or e/z/u-number."),
            )
        ],
        blank=True,
        null=True,
        unique=True,
    )

    starting_year = models.IntegerField(
        verbose_name=_("Starting year"),
        help_text=_("The year this member started studying."),
        blank=True,
        null=True,
    )

    # ---- Address information -----

    address_street = models.CharField(
        max_length=100,
        validators=[
            validators.RegexValidator(
                regex=r"^.+ \d+.*",
                message=_("please use the format <street> <number>"),
            )
        ],
        verbose_name=_("Street and house number"),
        null=True,
    )

    address_street2 = models.CharField(
        max_length=100, verbose_name=_("Second address line"), blank=True, null=True,
    )

    address_postal_code = models.CharField(
        max_length=10, verbose_name=_("Postal code"), null=True,
    )

    address_city = models.CharField(max_length=40, verbose_name=_("City"), null=True,)

    address_country = models.CharField(
        max_length=2, choices=countries.EUROPE, verbose_name=_("Country"), null=True,
    )

    phone_number = models.CharField(
        max_length=20,
        verbose_name=_("Phone number"),
        help_text=_("Enter a phone number so Thalia may reach you"),
        validators=[
            validators.RegexValidator(
                regex=r"^\+?\d+$", message=_("Please enter a valid phone number"),
            )
        ],
        null=True,
        blank=True,
    )

    # ---- Emergency contact ----

    emergency_contact = models.CharField(
        max_length=255,
        verbose_name=_("Emergency contact name"),
        help_text=_("Who should we contact in case of emergencies"),
        null=True,
        blank=True,
    )

website/members/templates/members/user/edit_profile.html
{% extends "base.html" %}
{% load static i18n fieldtype bootstrap4 alert %}

{% block title %}{% trans "edit profile"|capfirst %} — {% trans "members"|capfirst %} — {{ block.super }}{% endblock %}
{% block opengraph_title %}{% trans "edit profile"|capfirst %} — {% trans "members"|capfirst %} —
    {{ block.super }}{% endblock %}

{% block body %}
    <section class="page-section">
        <div class="container">
            <h1 class="text-center section-title">{% trans "edit profile"|capfirst %}</h1>

            {% if messages %}
                {% for message in messages %}
                    {% alert message.tags message %}
                {% endfor %}
            {% endif %}

            {% if form.errors %}
                {% trans "Please check your profile for errors." as error_text %}
                {% alert 'danger' error_text dismissible=True %}
            {% endif %}

            <form method="post" enctype="multipart/form-data" class="row">
                {% csrf_token %}

                <fieldset class="col-12 col-lg-6">
                    <div class="form-group">
                        <label>{% trans "First Name" %}</label>
                        <input type="text" class="form-control" readonly="readonly"
                               value="{{ request.member.first_name }}"/>
                    </div>

                    <div class="form-group">
                        <label>{% trans "Last Name" %}</label>
                        <input type="text" class="form-control" readonly="readonly"
                               value="{{ request.member.last_name }}"/>
                    </div>

                    <div class="form-group">
                        <label>{% trans "Email Address" %}</label>
                        <input type="text" class="form-control" readonly="readonly" value="{{ request.member.email }}"/>
                        <span class="form-text">
                            <a href="{% url 'members:email-change' %}">
                                {% trans "Click here to change your email address." %}
                            </a>
                        </span>
                    </div>

                    <div class="form-group">
                        <label>{% trans "Birthday" %}</label>
                        <input type="text" class="form-control" readonly="readonly"
                               value="{{ request.member.profile.birthday }}"/>
                    </div>

                    {% for field in form %}
                        {% if forloop.counter < 9 %}
                            {% bootstrap_field field %}
                        {% endif %}
                    {% endfor %}
                </fieldset>

                <fieldset class="col-12 col-lg-6">
                    {% for field in form %}
                        {% if forloop.counter > 8 %}
                            {% bootstrap_field field %}
                        {% endif %}
                    {% endfor %}
                </fieldset>

                <input type="submit" value="{% trans 'save'|capfirst %}" class="btn btn-primary col-6 offset-3 col-lg-2 offset-lg-10"/>
            </form>
        </div>
    </section>
{% endblock %}

website/members/templates/members/user/index.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block title %}{% trans "members"|capfirst %} — {{ block.super }}{% endblock %}
{% block opengraph_title %}{% trans "members"|capfirst %} — {{ block.super }}{% endblock %}

{% block body %}
    <section class="page-section">
        <div class="container">
            <h1 class="text-center section-title">{% trans 'Account' %}</h1>

            <div class="row">
                <div class="col-lg-6 offset-lg-3">

                    <p class="text-center">
                        {% blocktrans trimmed with user=request.member.username %}
                            You’re currently logged in as <strong>{{ user }}</strong>
                        {% endblocktrans %}.
                    </p>

                    <hr>

                    <div>
                        <a href="{% url 'members:profile' request.member.pk %}">{% trans "show public profile"|capfirst %}</a>
                        <p>{% blocktrans %}Take a look at your own profile.{% endblocktrans %}</p>
                    </div>

                    <hr>

                    <div>
                        <a href="{% url 'registrations:renew' %}">{% trans "manage membership"|capfirst %}</a>
                        <p>{% blocktrans %}Get information about your membership or renew it.{% endblocktrans %}</p>
                    </div>

                    <hr>

                    <div>
                        <a href="{% url 'members:edit-profile' %}">{% trans "edit profile"|capfirst %}</a>
                        <p>{% blocktrans %}Edit your profile and avatar.{% endblocktrans %}</p>
                    </div>

                    <hr>

                    <div>
                        <a href="{% url 'payments:bankaccount-list' %}">{% trans "manage bank account(s)"|capfirst %}</a>
                        <p>{% blocktrans %}Change the financial information known to Thalia.{% endblocktrans %}</p>
                    </div>

                    <hr>

                    <div>
                        <a href="{% url 'payments:payment-list' %}">{% trans "view payments"|capfirst %}</a>
                        <p>{% blocktrans %}Get an overview of all your expenses.{% endblocktrans %}</p>
                    </div>

                    <hr>

                    <div>
                        <a href="{% url 'password_change' %}">{% trans "change password"|capfirst %}</a>
                        <p>{% blocktrans %}Change your accounts' password.{% endblocktrans %}</p>
                    </div>

                    <hr>

                    <div>
                        <a href="{% url 'logout' %}">{% trans "logout"|capfirst %}</a>
                        <p>{% blocktrans %}Leave the restricted area of the website.{% endblocktrans %}</p>
                    </div>

                </div>
            </div>
        </div>
    </section>
{% endblock %}}

website/members/templates/members/user/profile.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block title %}{% trans "profile"|capfirst %} — {% trans "members"|capfirst %} — {{ block.super }}{% endblock %}
{% block opengraph_title %}{% trans "profile"|capfirst %} — {% trans "members"|capfirst %} —
    {{ block.super }}{% endblock %}

{% block body %}
    <section id="members-profile" class="page-section">
        <div class="container">
            <h1 class="text-center section-title">
                {{ member.profile.display_name }}
            </h1>

            <div class="row">
                <div class="col-12 col-lg-7 text-center">
                    {% if not member.profile.photo %}
                        <img src="{% static "members/images/default-avatar.jpg" %}"
                             alt="{{ member.profile.display_name }}"/>
                    {% else %}
                        <img src="{{ member.profile.photo.url }}"
                             alt="{{ member.profile.display_name }}"/>
                    {% endif %}
                </div>
                <div class="col-12 col-lg-5">
                    <h4>{% trans "About" %} {{ member.profile.short_display_name }}</h4>

                    {% if not member.profile.profile_description %}
                        <p>
                            <i>{% trans "This member has not written a description yet." %}</i>
                        </p>
                    {% else %}
                        {{ member.profile.profile_description }}
                    {% endif %}

                    <hr class="separator">

                    <h4>{% trans "Personal information" %}</h4>
                    <ul class="list-unstyled">
                        <li>
                            <strong>{% trans "Membership type" %}: </strong> {{ membership_type }}<br>
                        </li>

                        {% if member.profile.starting_year %}
                            <li>
                                <strong>{% trans "Cohort" %}: </strong> {{ member.profile.starting_year }}<br>
                            </li>
                        {% endif %}

                        {% if member.profile.programme %}
                            <li>
                                <strong>{% trans "Study programme" %}: </strong> {{ member.profile.get_programme_display }}<br>
                            </li>
                        {% endif %}

                        {% if member.profile.website %}
                            <li>
                                <strong>{% trans "Website" %}: </strong>
                                <a rel="nofollow,noopener" href="{{ member.profile.website }}">
                                    {{ member.profile.website }}
                                </a>
                            </li>
                        {% endif %}

                        {% if member.profile.show_birthday and member.profile.birthday %}
                            <li><strong>{% trans "Birthday" %}: </strong> {{ member.profile.birthday }}</li>
                        {% endif %}
                    </ul>

                    {% if achievements %}
                        <hr class="separator">
                        <h4>{% trans "Achievements for Thalia" %}</h4>
                        <ul class="list-unstyled">
                            {% for achievement in achievements %}
                                <li class="mb-1">
                                    <strong>
                                        {% if achievement.url %}
                                            <a href="{{ achievement.url }}">
                                                {{ achievement.name }}
                                            </a>
                                        {% else %}
                                            {{ achievement.name }}
                                        {% endif %}
                                    </strong>
                                    <br>
                                    {% for period in achievement.periods %}
                                        {% if period.role %}
                                            <span>{{ period.role }}: </span>
                                        {% elif period.chair %}
                                            <span>{% trans "Chair" %}: </span>
                                        {% endif %}
                                        <i>
                                            {% if period.since|date:'Y m d' == '1970 01 01' %}
                                                ?
                                            {% else %}
                                                {{ period.since }}
                                            {% endif %}
                                            -
                                            {% if period.until %}
                                                {{ period.until }}
                                            {% else %}
                                                {% trans "today" %}
                                            {% endif %}
                                        </i>
                                        <br>
                                    {% endfor %}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    {% if societies %}
                        <hr class="separator">
                        <h4>{% trans "Societies" %}</h4>
                        <ul class="list-unstyled">
                            {% for society in societies %}
                                <li class="mb-1">
                                    <strong>
                                        <a href="{{ society.url }}">
                                            {{ society.name }}
                                        </a>
                                    </strong>
                                    <br>
                                    {% for period in society.periods %}
                                        {% if period.role %}
                                            <span>{{ period.role }}: </span>
                                        {% elif period.chair %}
                                            <span>{% trans "Chair" %}: </span>
                                        {% endif %}
                                        <i>
                                            {% if period.since|date:'Y m d' == '1970 01 01' %}
                                                ?
                                            {% else %}
                                                {{ period.since }}
                                            {% endif %}
                                            -
                                            {% if period.until %}
                                                {{ period.until }}
                                            {% else %}
                                                {% trans "today" %}
                                            {% endif %}
                                        </i>
                                        <br>
                                    {% endfor %}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
        </div>
    </section>
{% endblock %}