website/events/urls.py
"""Routes defined by the events package"""
from django.urls import path, include

from events.feeds import EventFeed
from events.views import (
    EventIndex,
    EventDetail,
    EventRegisterView,
    RegistrationView,
    EventCancelView,
    AlumniEventsView,
    EventPayView,
)

app_name = "events"

urlpatterns = [
    path(
        "events/",
        include(
            [
                path("<int:pk>/", EventDetail.as_view(), name="event"),
                path(
                    "<int:pk>/registration/register/",
                    EventRegisterView.as_view(),
                    name="register",
                ),
                path(
                    "<int:pk>/registration/cancel/",
                    EventCancelView.as_view(),
                    name="cancel",
                ),
                path("<int:pk>/registration/pay/", EventPayView.as_view(), name="pay"),
                path(
                    "<int:pk>/registration/",
                    RegistrationView.as_view(),
                    name="registration",
                ),
                path("", EventIndex.as_view(), name="index"),
                path("ical/nl.ics", EventFeed(lang="nl"), name="ical-nl"),
                path("ical/en.ics", EventFeed(), name="ical-en"),
            ]
        ),
    ),
    path("association/alumni/", AlumniEventsView.as_view(), name="alumni"),
]

website/members/urls.py
"""The routes defined by the members package"""
from django.urls import path, include

from members.views import (
    MembersIndex,
    StatisticsView,
    ProfileDetailView,
    UserAccountView,
    UserProfileUpdateView,
    EmailChangeFormView,
    EmailChangeVerifyView,
    EmailChangeConfirmView,
)

app_name = "members"

urlpatterns = [
    path(
        "members/",
        include(
            [
                path("statistics/", StatisticsView.as_view(), name="statistics"),
                path("profile/<int:pk>", ProfileDetailView.as_view(), name="profile"),
                path("directory/<slug:filter>/", MembersIndex.as_view(), name="index"),
                path("directory/", MembersIndex.as_view(), name="index"),
            ]
        ),
    ),
    path(
        "user/",
        include(
            [
                path(
                    "edit-profile/",
                    UserProfileUpdateView.as_view(),
                    name="edit-profile",
                ),
                path(
                    "change-email/verify/<uuid:key>/",
                    EmailChangeVerifyView.as_view(),
                    name="email-change-verify",
                ),
                path(
                    "change-email/confirm/<uuid:key>/",
                    EmailChangeConfirmView.as_view(),
                    name="email-change-confirm",
                ),
                path(
                    "change-email/", EmailChangeFormView.as_view(), name="email-change"
                ),
                path("", UserAccountView.as_view(), name="user"),
            ]
        ),
    ),
]

website/registrations/urls.py
"""The routes defined by the registrations package"""
from django.urls import path, include
from django.views.generic import TemplateView

from .views import (
    BecomeAMemberView,
    ConfirmEmailView,
    EntryAdminView,
    MemberRegistrationFormView,
    RenewalFormView,
    BenefactorRegistrationFormView,
    ReferenceCreateView,
)

app_name = "registrations"

urlpatterns = [
    path(
        "registration/",
        include(
            [
                path(
                    "admin/process/<uuid:pk>/",
                    EntryAdminView.as_view(),
                    name="admin-process",
                ),
                path(
                    "confirm-email/<uuid:pk>/",
                    ConfirmEmailView.as_view(),
                    name="confirm-email",
                ),
                path(
                    "reference/<uuid:pk>/",
                    ReferenceCreateView.as_view(),
                    name="reference",
                ),
                path(
                    "reference/<uuid:pk>/success",
                    ReferenceCreateView.as_view(success=True),
                    name="reference-success",
                ),
            ]
        ),
    ),
    path(
        "user/membership/",
        include(
            [
                path("", RenewalFormView.as_view(), name="renew"),
                path(
                    "renew/success/",
                    TemplateView.as_view(
                        template_name="registrations/renewal_success.html"
                    ),
                    name="renew-success",
                ),
            ]
        ),
    ),
    path(
        "association/",
        include(
            [
                path("register/", BecomeAMemberView.as_view(), name="index"),
                path(
                    "register/member/",
                    MemberRegistrationFormView.as_view(),
                    name="register-member",
                ),
                path(
                    "register/benefactor/",
                    BenefactorRegistrationFormView.as_view(),
                    name="register-benefactor",
                ),
                path(
                    "register/success/",
                    TemplateView.as_view(
                        template_name="registrations/register_success.html"
                    ),
                    name="register-success",
                ),
            ]
        ),
    ),
]

website/singlepages/urls.py
"""Defines the routes provided in this package"""
from django.urls import path, include

from .views import (
    PrivacyPolicyView,
    EventTermsView,
    SiblingAssociationsView,
    BecomeActiveView,
    StyleGuideView,
    ContactView,
    AlmanacView,
)

app_name = "singlepages"

urlpatterns = [
    path("privacy-policy/", PrivacyPolicyView.as_view(), name="privacy-policy"),
    path(
        "event-registration-terms/",
        EventTermsView.as_view(),
        name="event-registration-terms",
    ),
    path(
        "association/",
        include(
            [
                path(
                    "sibling-associations/",
                    SiblingAssociationsView.as_view(),
                    name="sibling-associations",
                )
            ]
        ),
    ),
    path(
        "members/",
        include(
            [
                path(
                    "become-active/", BecomeActiveView.as_view(), name="become-active"
                ),
                path("styleguide/", StyleGuideView.as_view(), name="styleguide"),
                path("almanac/", AlmanacView.as_view(), name="almanac"),
            ]
        ),
    ),
    path("contact", ContactView.as_view(), name="contact"),
]

website/thaliawebsite/urls.py
import os.path

from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.contrib.sitemaps.views import sitemap
from django.urls import path, re_path
from django.views.i18n import JavaScriptCatalog

from activemembers.sitemaps import sitemap as activemembers_sitemap
from documents.sitemaps import sitemap as documents_sitemap
from education.sitemaps import sitemap as education_sitemap
from events.sitemaps import sitemap as events_sitemap
from members.sitemaps import sitemap as members_sitemap
from members.views import ObtainThaliaAuthToken
from partners.sitemaps import sitemap as partners_sitemap
from singlepages.sitemaps import sitemap as singlepages_sitemap
from thabloid.sitemaps import sitemap as thabloid_sitemap
from thaliawebsite.forms import AuthenticationForm
from thaliawebsite.views import TestCrashView, IndexView
from utils.media.views import generate_thumbnail, private_media
from .sitemaps import StaticViewSitemap

__all__ = ["urlpatterns"]

THALIA_SITEMAP = {
    "main-static": StaticViewSitemap,
}
THALIA_SITEMAP.update(activemembers_sitemap)
THALIA_SITEMAP.update(members_sitemap)
THALIA_SITEMAP.update(documents_sitemap)
THALIA_SITEMAP.update(thabloid_sitemap)
THALIA_SITEMAP.update(partners_sitemap)
THALIA_SITEMAP.update(education_sitemap)
THALIA_SITEMAP.update(events_sitemap)
THALIA_SITEMAP.update(singlepages_sitemap)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    # Default helpers
    path(
        "user/",
        include(
            [
                path(
                    "login/",
                    LoginView.as_view(
                        authentication_form=AuthenticationForm,
                        redirect_authenticated_user=True,
                    ),
                    name="login",
                ),
                path("", include("django.contrib.auth.urls")),
            ]
        ),
    ),
    path(
        "i18n/",
        include(
            [
                path("", include("django.conf.urls.i18n")),
                path("js/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
            ]
        ),
    ),
    # Apps
    path("", include("singlepages.urls")),
    path("", include("merchandise.urls")),
    path("", include("thabloid.urls")),
    path("", include("registrations.urls")),
    path("", include("newsletters.urls")),
    path("", include("announcements.urls")),
    path("", include("pushnotifications.urls")),
    path("", include("photos.urls")),
    path("", include("members.urls")),
    path("", include("payments.urls")),
    path("", include("education.urls")),
    path("", include("activemembers.urls")),
    path("", include("documents.urls")),
    path("", include("events.urls")),
    path("", include("pizzas.urls")),
    path("", include("partners.urls")),
    # App API
    path(
        "api/v1/",
        include(
            [
                path("token-auth/", ObtainThaliaAuthToken.as_view()),
                path("", include("activemembers.api.urls")),
                path("", include("events.api.urls")),
                path("", include("members.api.urls")),
                path("", include("partners.api.urls")),
                path("", include("pizzas.api.urls")),
                path("", include("photos.api.urls")),
                path("", include("pushnotifications.api.urls")),
            ]
        ),
    ),
    # Sitemap
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": THALIA_SITEMAP},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    # Dependencies
    path(r"tinymce", include("tinymce.urls")),
    # Provide something to test error handling. Limited to admins.
    path("crash/", TestCrashView.as_view()),
    # Custom media paths
    re_path(
        r"^media/generate-thumbnail/(?P<request_path>.*)",
        generate_thumbnail,
        name="generate-thumbnail",
    ),
    re_path(
        r"^media/private/(?P<request_path>.*)$", private_media, name="private-media"
    ),
] + static(
    settings.MEDIA_URL + "public/",
    document_root=os.path.join(settings.MEDIA_ROOT, "public"),
)

website/thaliawebsite/forms.py
"""Special forms"""
from django.contrib.auth.forms import AuthenticationForm as BaseAuthenticationForm


class AuthenticationForm(BaseAuthenticationForm):
    """Override the authentication form provided by Django"""

    def clean(self):
        """Lowercase the username"""
        if "username" in self.cleaned_data:
            self.cleaned_data["username"] = self.cleaned_data["username"].lower()
        super().clean()

website/thaliawebsite/views.py
"""General views for the website"""

from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponseForbidden, HttpResponse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.views.generic.base import View


class IndexView(TemplateView):
    template_name = "index.html"


@method_decorator(staff_member_required, "dispatch")
class TestCrashView(View):
    """Test view to intentionally crash to test the error handling."""

    def dispatch(self, request, *args, **kwargs) -> HttpResponse:
        if not request.user.is_superuser:
            return HttpResponseForbidden("This is not for you")
        raise Exception("Test exception")

website/thaliawebsite/templates/base.html
{% load i18n static menu compress pick_header_image %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>{% block title %}
        {% trans "Study Association Thalia" %}{% endblock %}</title>

    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="theme-color" content="#E62272"/>
    {% if debug %}
        <link rel="icon" href="{% static "img/browser/icon-debug.png" %}">
    {% else %}
        <link rel="icon" href="{% static "img/browser/icon.png" %}">
    {% endif %}
    <link rel="apple-touch-icon" href="{% static "img/browser/icon.png" %}">
    <meta name="msapplication-square70x70logo"
          content="{% static "img/browser/icon-smalltile.png" %}">
    <meta name="msapplication-square150x150logo"
          content="{% static "img/browser/icon-mediumtile.png" %}">
    <meta name="msapplication-wide310x150logo"
          content="{% static "img/browser/icon-widetile.png" %}">
    <meta name="msapplication-square310x310logo"
          content="{% static "img/browser/icon-largetile.png" %}">

    <meta property="og:image"
          content="{% if request.is_secure %}https://{% else %}http://{% endif %}{{ request.get_host }}{% static "img/browser/icon-largetile.png" %}"/>
    <meta property="og:type" content="website"/>
    <meta property="og:title"
          content="{% block opengraph_title %}{% trans 'Study Association Thalia' %}{% endblock %}"/>
    {% block opengraph %}{% endblock %}

    {% block css_head %}
        {% compress css %}
            <link href="{% static "css/main.scss" %}" rel="stylesheet"
                  type="text/x-scss">
            <link href="{% static "css/main-dark.scss" %}" rel="stylesheet" media="(prefers-color-scheme: dark)"
                  type="text/x-scss">
        {% endcompress %}
    {% endblock %}

    {% block js_head %}
    {% endblock %}

    <!-- build commit: {{ SOURCE_COMMIT }} -->
</head>
<body class="{% block body_class %}{% endblock %}">

<section id="announcements-alerts">
    {% if request.member and request.member.current_membership is None %}
        <div class="announcement">
            <i class="fas fa-id-card"></i>
            <p>
                <a href="{% url 'registrations:renew' %}">
                    {% trans "You're currently not a member of Thalia. Renew your membership to get access to all parts of the website." %}
                </a>
            </p>
        </div>
    {% elif request.member and request.member.profile.event_permissions != "all" %}
        <div class="announcement">
            <p>
                {% blocktrans trimmed %}
                You're currently not allowed to go to certain events. Please contact Thalia's
                <a href="mailto:treasurer@thalia.nu">treasurer</a> for more information.
                {% endblocktrans %}
            </p>
        </div>
    {% endif %}
    {% include "announcements/announcement.html" with announcements=announcements %}
</section>

<div id="accentbar"></div>

<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">
            <picture>
                <source srcset="{% static 'img/logo-'|add:LANGUAGE_CODE|add:'-dark.svg' %}" media="(prefers-color-scheme: dark)">
                <source srcset="{% static 'img/logo-'|add:LANGUAGE_CODE|add:'.svg' %}" media="(prefers-color-scheme: light)">
                <img
                    src="{% static 'img/logo-'|add:LANGUAGE_CODE|add:'.svg' %}"
                    id="logo"
                    alt="{% trans 'Study Association Thalia' %}"
                    height="220px"
                >
            </picture>
        </a>
        <div class="flex-grow-1"></div>
        <div class="navbar-user order-1 d-flex">
            <a href="#lang"
               class="btn btn-link"
               id="language-switcher">
                {% if LANGUAGE_CODE == 'nl' %}
                    <img src="{% static 'img/flags/en.svg' %}"/>
                {% else %}
                    <img src="{% static 'img/flags/nl.svg' %}"/>
                {% endif %}
            </a>
            <div class="btn-group">
                {% if not user.is_authenticated %}
                    <a href="{% url 'login' %}" class="btn btn-primary"><i
                        class="fas fa-user"></i></a>
                {% else %}
                    <a href="{% url 'members:user' %}" class="btn btn-primary"><i
                        class="fas fa-user"></i></a>
                    <button type="button"
                            class="btn btn-primary dropdown-toggle dropdown-toggle-split"
                            data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false"></button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item"
                           href="{% url 'members:edit-profile' %}">{% trans "edit profile"|capfirst %}</a>
                        <a class="dropdown-item"
                           href="{% url 'password_change' %}">{% trans "change password"|capfirst %}</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item"
                           href="{% url 'admin:index' %}">{% trans "Site administration" %}</a>
                        <a class="dropdown-item"
                           href="{% url 'logout' %}">{% trans "Log Out" %}</a>
                    </div>
                {% endif %}
            </div>
        </div>
        <button class="navbar-toggler order-0 justify-content-end"
                type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false"
                aria-label="Toggle navigation"><i class="fa fa-bars"></i>
        </button>
        <div
            class="collapse navbar-collapse justify-content-end order-lg-0 order-2"
            id="navbarCollapse">
            {% render_main_menu %}
        </div>
    </div>
</nav>

<header id="page-header">
    {% block header_image_container %}
        <img src="

            {% block header_image %}{% pick_header_image %}{% endblock header_image %}"
             class="image"/>
    {% endblock header_image_container %}
</header>

{% block pre-body %}{% endblock pre-body %}

<div id="page-content" class="clearfix">
    {% block body %}{% endblock body %}
</div>

{% block post-body %}{% endblock post-body %}

<footer>
    <div
        class="container d-flex justify-content-md-between align-items-center flex-md-row flex-column">
        <div class="copyright">
            <strong>Copyright {% now "Y" %} {% trans 'Study Association Thalia' %}</strong>
            <span class="divider">&#9679;</span>
            <a href="{% url 'singlepages:privacy-policy' %}">{% trans "privacy policy"|capfirst %}</a>
        </div>
        <div class="social float-right">
            <a target="_blank" rel="noopener" href="https://www.facebook.com/svThalia">
                <i class="fab fa-facebook"></i>
            </a>
            <a target="_blank" rel="noopener" href="https://twitter.com/svThalia">
                <i class="fab fa-twitter"></i>
            </a>
            <a target="_blank" rel="noopener" href="http://www.linkedin.com/groups?gid=54887">
                <i class="fab fa-linkedin"></i>
            </a>
            <a target="_blank" rel="noopener" href="https://gitlab.science.ru.nl/thalia/">
                <i class="fab fa-gitlab"></i>
            </a>
        </div>
    </div>
</footer>

<form method="post" action="{% url 'set_language' %}" class="d-none"
      id="change-language-form">
    {% csrf_token %}
    <input type="hidden" value="{{ request.get_full_path }}" name="next"/>
    <input type="hidden"
           value="{% if LANGUAGE_CODE == 'nl' %}en{% else %}nl{% endif %}"
           name="language"/>
</form>

{% block js_body %}
    <script type="text/javascript"
            src="{% url 'javascript-catalog' %}"></script>
    {% compress js %}
        <script type="text/javascript"
                src="{% static "js/jquery.min.js" %}"></script>
        <script type="text/javascript"
                src="{% static "js/js.cookie.min.js" %}"></script>
        <script type="text/javascript"
                src="{% static "js/bootstrap.bundle.min.js" %}"></script>
        <script type="text/javascript"
                src="{% static "js/jquery.fancybox.min.js" %}"></script>
        <script type="text/javascript"
                src="{% static "js/main.js" %}"></script>
        <script type="text/javascript"
                src="{% static "announcements/js/announcements.js" %}"></script>
    {% endcompress %}
{% endblock %}
</body>
</html>

website/thaliawebsite/templates/error.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Error — {{ block.super }}{% endblock %}
{% block opengraph_title %}Error — {{ block.super }}{% endblock %}

{% block body %}
    <section id="thaliawebsite-error" class="page-section">
        <div class="container">
            <h1 class="text-center section-title">{% blocktrans %}Error{% endblocktrans %}</h1>
            <p class="text-center">{% block error_message %}{% trans "An error occurred." %}{% endblock %}</p>
            <p class="text-center">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/t3otBjVZzT0?autoplay=0"
                        frameborder="0" allowfullscreen></iframe>
            </p>
        </div>
    </section>
{% endblock %}

website/thaliawebsite/templates/index.html
{% extends 'base.html' %}
{% load i18n event_cards frontpage_articles partner_banners slider %}

{% block body_class %}home{% endblock %}

{% block header_image_container %}
    {% render_slider %}
{% endblock header_image_container %}

{% block pre-body %}
    {% render_partner_banners %}
{% endblock %}

{% block body %}
    <section id="thaliawebsite-frontpage" class="page-section">
        <div class="container">
            <h1 class="text-center section-title">{% trans "Study Association Thalia" %}</h1>
            <p class="text-center">{% blocktrans %}Thalia is the study association for the Computing Science and Information Sciences students at Radboud University in Nijmegen. Thalia provides you the necessary distractions during your studies. And via Thalia students can easily connect with teachers and students from other years.{% endblocktrans %}</p>
        </div>
    </section>

    {% render_frontpage_articles %}
    {% render_event_cards %}
{% endblock %}